In [35]:
import numpy as np
import matplotlib.pyplot as plt

In [36]:
numTrials = 100

In [37]:
filenames = ['theory_' + str(i) + '.txt' for i in range(numTrials)]

In [38]:
trials = [np.loadtxt(filename) for filename in filenames]

In [39]:
i = 4
j = 5

In [40]:
[i for i, trial in enumerate(trials) if trial[0][-1] == 3]

[9, 38, 48, 74, 78, 96]

In [43]:
trials[0][0]

array([1., 4., 3., 4., 5., 4.])

In [30]:
trials[9][0]

array([3., 3., 3., 4., 5., 3.])

In [32]:
trial = trials[9]
trial[:, j] - trial[:, i]

array([-2.00000e+00,  2.72730e-01,  1.27270e+00,  2.27270e+00,
        4.58090e+00,  6.56720e+00,  8.55360e+00,  1.05399e+01,
        1.14298e+01,  1.24298e+01,  1.37823e+01,  1.47010e+01,
        1.58575e+01,  1.66851e+01,  1.77116e+01,  1.85489e+01,
        1.97825e+01,  2.08077e+01,  2.19945e+01,  2.29945e+01,
        2.39945e+01,  2.51970e+01,  2.55620e+01,  2.67130e+01,
        2.76610e+01,  2.85360e+01,  2.95360e+01,  3.06380e+01,
        3.13110e+01,  3.19840e+01,  3.33190e+01,  3.42100e+01,
        3.46750e+01,  3.62000e+01,  3.72000e+01,  3.76800e+01,
        3.91890e+01,  4.01890e+01,  4.16950e+01,  4.27800e+01,
        4.38940e+01,  4.52010e+01,  4.66860e+01,  4.77940e+01,
        4.88420e+01,  4.99590e+01,  5.09590e+01,  5.24130e+01,
        5.34620e+01,  5.47460e+01,  5.58230e+01,  5.68230e+01,
        5.78230e+01,  5.88230e+01,  5.99430e+01,  6.08720e+01,
        6.18720e+01,  6.26300e+01,  6.37420e+01,  6.45040e+01,
        6.55040e+01,  6.64870e+01,  6.75950e+01,  6.858

In [58]:
Ds = []
t = 1
for trial in trials:
    Ds.append((trial[:, j] - trial[:, i])[t])

In [59]:
Ds

[-2.0,
 1.0,
 3.5,
 2.36364,
 -0.25,
 2.36364,
 1.0,
 -3.33333,
 1.7857299999999992,
 0.27273000000000014,
 3.88889,
 3.22222,
 -0.6666699999999999,
 2.5,
 0.0,
 3.33333,
 2.0,
 -2.58974,
 0.9462299999999999,
 -3.33333,
 -1.92307,
 1.6750000000000007,
 3.44763,
 1.0,
 1.2083300000000001,
 1.0,
 -1.3333300000000001,
 -3.2795700000000005,
 0.5632199999999994,
 3.33333,
 1.875,
 2.2941000000000003,
 0.5999999999999996,
 -0.44444000000000017,
 1.8461300000000005,
 5.375,
 -2.41441,
 2.0,
 -3.818180000000001,
 1.8571899999999992,
 2.4561399999999995,
 0.0,
 1.7857299999999992,
 0.7618999999999998,
 2.1505399999999995,
 0.3333300000000001,
 -1.4166699999999999,
 -2.58333,
 -1.0,
 5.72723,
 4.0,
 2.0,
 1.6666699999999999,
 2.4000000000000004,
 4.0,
 0.0,
 3.57144,
 3.5315700000000003,
 3.44763,
 4.433330000000001,
 3.66667,
 -0.3636400000000002,
 0.7058800000000005,
 3.66667,
 2.0625,
 5.85057,
 6.0,
 -1.9166600000000003,
 5.3,
 -0.053770000000000095,
 0.5,
 2.0,
 2.66667,
 1.0406499999999994

In [60]:
sum([x >= 0 for x in Ds])/len(Ds)

0.73

In [47]:
3/4

0.75

In [48]:
len(Ds)

100

In [61]:
(3/4)**2 + (1/4) * (1/2)

0.6875

In [62]:
3/4

0.75

In [70]:
def f(x):
    return x * (3/4) + (1-x) * (1/2)

In [71]:
def g(t):
    x = 3/4
    for _ in range(t):
        x = f(x)
    return x

In [78]:
n = 100
x = 1-a(n, n/4)
print(x)
#g(20000)

NameError: name 'a' is not defined